In [1]:
from dados_api import previsao_temperatura

In [12]:
df1, df2 = previsao_temperatura(40.41954336668318, -3.685728034780609)

Coordinates: 40.39598846435547°N -3.679344654083252°E
Elevation: 669.0 m asl
Timezone difference to GMT+0: 0s

Hourly data
                          date  temperature_2m
0   2026-10-22 00:00:00+00:00        9.733500
1   2026-10-22 01:00:00+00:00        9.133499
2   2026-10-22 02:00:00+00:00        8.683500
3   2026-10-22 03:00:00+00:00        8.333500
4   2026-10-22 04:00:00+00:00        7.933500
..                        ...             ...
163 2026-10-28 19:00:00+00:00       14.772500
164 2026-10-28 20:00:00+00:00       14.422500
165 2026-10-28 21:00:00+00:00       14.172500
166 2026-10-28 22:00:00+00:00       14.022500
167 2026-10-28 23:00:00+00:00       13.922500

[168 rows x 2 columns]

In [6]:
df1

                         date  temperature_2m  dia  mes    dia_semana
0   2026-10-22 00:00:00+00:00        9.733500   22   10  Quinta-feira
1   2026-10-22 01:00:00+00:00        9.133499   22   10  Quinta-feira
2   2026-10-22 02:00:00+00:00        8.683500   22   10  Quinta-feira
3   2026-10-22 03:00:00+00:00        8.333500   22   10  Quinta-feira
4   2026-10-22 04:00:00+00:00        7.933500   22   10  Quinta-feira
..                        ...             ...  ...  ...           ...
163 2026-10-28 19:00:00+00:00       14.772500   28   10  Quarta-feira
164 2026-10-28 20:00:00+00:00       14.422500   28   10  Quarta-feira
165 2026-10-28 21:00:00+00:00       14.172500   28   10  Quarta-feira
166 2026-10-28 22:00:00+00:00       14.022500   28   10  Quarta-feira
167 2026-10-28 23:00:00+00:00       13.922500   28   10  Quarta-feira

[168 rows x 5 columns]

In [7]:
df2

   dia  mes     dia_semana  temperatura_media
0   22   10   Quinta-feira          12.891833
1   23   10    Sexta-feira          14.148083
2   24   10         Sábado          12.050166
3   25   10        Domingo          13.773084
4   26   10  Segunda-feira          14.323083
5   27   10    Terça-feira          14.449124
6   28   10   Quarta-feira          14.360000